### PR TITLE
fix: Allow asset download from private repos

### LINKED ISSUE #18: dispatch doesn't work with private GitHub repos
dispatch can list GitHub Release Assets in private repos, but cannot download them.

### PR DESCRIPTION
**Pull request by markg-github**
Allow asset download from private repos: use URL with asset ID, supply token, etc.
Use --public to download in a way (the old way) that only works for public repos.

Resolves: #18

### CODE REVIEW

File: src/http/service.rs [hunk 1]
```diff
@@ -45,6 +45,46 @@ impl Service {
...
+        } else {
+            asset.url.clone()
+        };
+
+        let rb = match method {
+            &Method::HEAD => client.head(url),
+            _ => client.get(url), // fallback; you only use HEAD/GET here
+        };
+
+        if gh.is_private() {
```
Comment (amd-aliem) [inline src/http/service.rs]: I think this can be removed after you fix the other accept header

File: src/http/server.rs [hunk 2]
```diff
@@ -49,11 +49,31 @@ impl Server {
             attempt.stop()
         });
 
+        let mut client_builder = Client::builder().redirect(policy);
+        if github.is_private() {
+            // Build client with GitHub authentication if token is available
+            if let Some(token) = github.token() {
+                let mut headers = reqwest::header::HeaderMap::new();
+                headers.insert("Authorization", format!("token {token}").parse().unwrap());
```
Comment (amd-aliem) [inline src/http/server.rs]: docs suggest marking tokens as secret:
```
// Consider marking security-sensitive headers with `set_sensitive`.
let mut auth_value = header::HeaderValue::from_static("secret");
auth_value.set_sensitive(true);
headers.insert(header::AUTHORIZATION, auth_value);
```

File: src/http/service.rs (hunk 1 above)
Comment (markg-github) [reply src/http/service.rs]: Good catch. Thanks.

File: src/http/server.rs [hunk 3]
```diff
@@ -49,11 +49,35 @@ impl Server {
...
+                client_builder = client_builder.default_headers(headers);
+            }
+        }
+
         Ok(Self {
             listener,
             status,
             github,
-            client: Client::builder().redirect(policy).build()?,
+            client: client_builder.build()?,
```
Comment (amd-aliem) [inline src/http/server.rs:80]: Is there a reason that private would not need the redirect policy? Otherwise I think you keep the redirect() call here and remove the one at the top.

File: src/http/service.rs [hunk 4]
```diff
@@ -122,9 +176,20 @@ impl hyper::service::Service<Request<Incoming>> for Service {
...
-                            let response = client.get(asset.url).send().await?;
-                            status.lock().await.update().downloading(remote);
-                            (response, asset.mime)
+                            let request =
+                                Self::build_request(&github, &asset, &client, &Method::GET);
+
+                            match request.send().await {
+                                Ok(resp) => {
+                                    let (_status_code, _content_length) =
+                                        Self::inspect_response(&resp);
```
[the remark this answers is not in the document]
Comment (amd-aliem) [reply src/http/service.rs]: @markg-github is there a reason for not removing these? I agree w/ the copilot comments that I can't see why we'd want to inspect the response if nothing is done with the contents. Was this done for debug and then forgot to remove? The original implementation was pretty nice and concise.

[the remark this answers is not in the document]
Comment (markg-github) [reply src/http/service.rs]: I thought I was preserving original behavior, but, in fact, I was preserving intermediate behavior. I'll remove.

File: src/http/server.rs (hunk 3 above)
Comment (markg-github) [reply src/http/server.rs:80]: I believe the redirect policy is still there. The client_builder assignment that happens only when the repo is private builds on the original client_builder assignment, which has the redirect policy.

Comment (amd-aliem) [reply src/http/server.rs:80]: Missed that :)

File: src/http/service.rs [hunk 5]
```diff
@@ -122,9 +157,18 @@ impl hyper::service::Service<Request<Incoming>> for Service {
...
+
+                            match request.send().await {
+                                Ok(resp) => {
+                                    status.lock().await.update().downloading(remote);
+                                    (resp, asset.mime)
+                                }
+                                Err(_e) => {
+                                    return Ok(EMPTY.reply(Code::BAD_GATEWAY, None, None));
+                                }
+                            }
```
Comment (amd-aliem) [inline src/http/service.rs]:
```suggestion
                            let response = request.send().await?;
                            status.lock().await.update().downloading(remote);
                            (response, asset.mime)
```

Comment (amd-aliem) [reply src/http/service.rs]: Imo original code is nice in its conciseness - Isn't the change hiding the actual error code? Would rather see the 404 or 429 or whatever instead of bad_gateway

Comment (markg-github) [reply src/http/service.rs]: Agree and will update shortly.

Comment (markg-github) [reply src/http/service.rs]: Done

**Review by amd-aliem — APPROVED** [review]
